language: bash

services:
  - docker

install:
  - docker build --tag "magic_castle-ui:latest" .

script:
  - docker run --env-file ./env.list --publish 5000:5000 "magic_castle-ui:latest" python -m pytest
