version: '3.8'

services:
  web:
    build:
      context: .
      target: production-server
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./clusters_backup
        target: /home/mcu/clusters
    user: mcu
