version: "3.8"

services:
  web:
    build:
      context: .
      target: production-server
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./clusters_backup
        target: /home/mcu/clusters
      - type: bind
        source: ./configuration.json
        target: /home/mcu/configuration.json
      - type: volume
        source: database
        target: /home/mcu/database
      - type: bind
        source: ./gcloud-key.json
        target: /home/mcu/credentials/gcloud-key.json
      - type: bind
        source: ./clouds.yaml
        target: /home/mcu/.config/openstack/clouds.yaml
        read_only: true
    user: mcu

volumes:
  database: